const express = require('express')
const app = express()
const {server} = require('./config/index')
app.use(express.json())
app.use(express.urlencoded({extended:false}))
const api = require('./routers/index')
app.use('/api',api)
app.listen(server.PORT,()=>{
    console.log(`listening to the port *${server.PORT}`)
})